### ISSUE TITLE
Hunting Down Errors (When Trying To Implement In Atom)

### ISSUE THREAD

**Issue by mikebronner** [bmewburn/intelephense-server#2]
Hi Ben,

I have been making progress on my implementation with Atom editor, but am running into the following error:
```
PHP (intelephense-server) rpc.sendRequest initialize threw Error: Request initialize failed with message: Cannot read property 'storagePath' of undefined
    at new ResponseError (/Users/mike/Developer/ide-laravel/node_modules/vscode-jsonrpc/lib/messages.js:46)
    at handleResponse (/Users/mike/Developer/ide-laravel/node_modules/vscode-jsonrpc/lib/main.js:430)
    at processMessageQueue (/Users/mike/Developer/ide-laravel/node_modules/vscode-jsonrpc/lib/main.js:258)
    at Immediate.<anonymous> (/Users/mike/Developer/ide-laravel/node_modules/vscode-jsonrpc/lib/main.js:242)
    at runCallback (timers.js:651)
    at tryOnImmediate (timers.js:624)
    at processImmediate [as _immediateCallback] (timers.js:596)
```

How can I pass `storagePath` in via the command-line? Thanks!

**UPDATE**: I seem to have solved this by defining a `getInitializeParams` method. Not sure if this is correct, but now it gives me a different error (see next comment).
```js
    getInitializeParams()
    {
        return {
            initializationOptions: {
                storagePath: "/tmp"
            }
        };
    }
```

**Comment by mikebronner** [comment]
Seems I got a step further, now I'm getting this error:
```
PHP (intelephense-server) rpc.sendRequest initialize threw Error: Request initialize failed with message: Cannot read property 'workspace' of undefined
    at new ResponseError (/Users/mike/Developer/ide-laravel/node_modules/vscode-jsonrpc/lib/messages.js:46)
    at handleResponse (/Users/mike/Developer/ide-laravel/node_modules/vscode-jsonrpc/lib/main.js:430)
    at processMessageQueue (/Users/mike/Developer/ide-laravel/node_modules/vscode-jsonrpc/lib/main.js:258)
    at Immediate.<anonymous> (/Users/mike/Developer/ide-laravel/node_modules/vscode-jsonrpc/lib/main.js:242)
    at runCallback (timers.js:651)
    at tryOnImmediate (timers.js:624)
    at processImmediate [as _immediateCallback] (timers.js:596)
```

**Comment by mikebronner** [comment]
The next error I'm working through is this one:
```
Uncaught (in promise) Error: spawn ENOTDIR
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at Object.exports.spawn (child_process.js:399:9)
    at PhpLanguageClient.spawnChildNode (/Users/mike/Developer/ide-laravel/node_modules/atom-languageclient/build/lib/auto-languageclient.js:283:15)
    at PhpLanguageClient.startServerProcess (/Users/mike/Developer/ide-laravel/lib/main.js:40:22)
    at PhpLanguageClient.startServer (/Users/mike/Developer/ide-laravel/node_modules/atom-languageclient/build/lib/auto-languageclient.js:296:28)
    at ServerManager._serverManager._serverManager.ServerManager.p [as _startServer] (/Users/mike/Developer/ide-laravel/node_modules/atom-languageclient/build/lib/auto-languageclient.js:261:70)
    at ServerManager.startServer (/Users/mike/Developer/ide-laravel/node_modules/atom-languageclient/build/lib/server-manager.js:144:34)
    at ServerManager.getServer (/Users/mike/Developer/ide-laravel/node_modules/atom-languageclient/build/lib/server-manager.js:139:73)
    at ServerManager._handleTextEditor (/Users/mike/Developer/ide-laravel/node_modules/atom-languageclient/build/lib/server-manager.js:81:33)
    at ServerManager._handleGrammarChange (/Users/mike/Developer/ide-laravel/node_modules/atom-languageclient/build/lib/server-manager.js:96:12)
    at editor.observeGrammar.grammar (/Users/mike/Developer/ide-laravel/node_modules/atom-languageclient/build/lib/server-manager.js:72:60)
    at TextEditor.observeGrammar (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:728:11)
    at ServerManager.observeTextEditors (/Users/mike/Developer/ide-laravel/node_modules/atom-languageclient/build/lib/server-manager.js:72:29)
    at Set.forEach (native)
    at TextEditorRegistry.observe (/Applications/Atom.app/Contents/Resources/app/src/text-editor-registry.js:134:24)
    at ServerManager.startListening (/Users/mike/Developer/ide-laravel/node_modules/atom-languageclient/build/lib/server-manager.js:55:45)
    at PhpLanguageClient.activate (/Users/mike/Developer/ide-laravel/node_modules/atom-languageclient/build/lib/auto-languageclient.js:262:25)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:230:33)
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:206:33)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at activationPromise.Promise (/Applications/Atom.app/Contents/Resources/app/src/package.js:200:20)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:695:42)
    at config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:670:36)
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:647:50)
    at loadStatePromise.loadState.then (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:841:27)
```

**Comment by mikebronner** [comment]
I now seem to be able to get some hints when typing. However, there seems to be something wrong with the resolution of hints if I backspace. I attempted to record what is happening here: https://vimeo.com/258552595

I would love to hear you feedback and ideas of what I might try next. Thanks!

**Comment by bmewburn** [comment]
Hi @mikebronner , nice work! I think there are a couple of things happening that could be limiting suggestions. Firstly there is no workspace indexing, so you will only get suggestions for files that you have opened, see #1 .  Secondly, I think the parser is not recovering properly from the below error which means that methods declared after this error are not being read. 
```php
$this-> //this is being read as an if method
if($a && $b) { }
```
So there's a couple of things that need to be improved in this library.

**Comment by mikebronner** [comment]
@bmewburn Thanks so much for your response! The workspace indexing: is that something I need to specify in the configuration, or is that a current limitation of Intelephense? How do you handle that in VSCODE?
Regarding the error: you are right, that is the behavior I was seeing: nothing after the line I was editing was available for completion.

I'll see if I can poke around in the server logic and maybe submit a PR or two to help out, time permitting. :)

**Comment by bmewburn** [comment]
The workspace indexing is currently driven by the client, so it needs to be moved out of vscode-intelephense and into intelephense-server so that other clients dont have to re-implement it. It's largely just a copy and paste job but I have a large change coming in how type inference works which is blocking this for now.

**Comment by mikebronner** [comment]
Gotcha! I'll hold off for now. :) Looking forward to your updates.

**Comment by mikebronner** [comment]
Should we keep this open to track the syntax issue preventing it from scanning the rest of the file?

**Comment by mikebronner** [comment]
nah, will create new issue to keep it clean.
